### ISSUE TITLE
[FR] Option to hide "more info" dialogs entirely

### ISSUE THREAD

**Issue by ebroder** [NemesisRE/kiosk-mode#129]
**Is your feature request related to a problem? Please describe.**

For my kiosk deployment, I really don't want users navigating away from the main dashboard page, and there are a lot of ways to do that from the various elements in the more-info dialogs. Currently, there are several options for hiding individual elements in the more-info dialog. However, there's no way to hide the three dot button on the card entirely.

**Describe the solution you'd like**

It'd be great if there was an option (`hide_dialog_button`? Not sure on the name) that completely suppressed the three dot menu in the top-right of cards like thermostat or light.

**Describe alternatives you've considered**

I can go through and set an assortment of options to try and prevent anything that navigates away from the dashboard page. However, there are a lot of options to cover, and that approach isn't robust to new functionality in newer versions of HA.

I can avoid using any cards that have a kebab menu button, but that's very limiting in terms of what dashboards I can build for my kiosks.

**Comment by elchininet** [comment]
Hi @ebroder,
Please, consult [this discussion](https://github.com/NemesisRE/kiosk-mode/discussions/128) and anything that you want to discuss, do it there. `kiosk-mode` is not intended to modify cards, that would not be realistic because there are an huge number of cards, with dfiferent structure and they change constantly on every version. Anything that you want to modify in your cards could be done using [card-mod](https://github.com/thomasloven/lovelace-card-mod), you can even use [jinja templates](https://www.home-assistant.io/docs/configuration/templating/#reusing-templates) to apply repetitive styles in different cards.
Regards

**Comment by elchininet** [comment]
Hi @ebroder,
[In this new document](https://github.com/NemesisRE/kiosk-mode/blob/master/KIOSK-MODE-COMPLEMENTS.md#hide-more-info-button-on-some-native-home-assistant-cards) for `kiosk-mode` complements you can find the `card-mod` code to achieve what you wanted to do.
Regards

**Comment by ebroder** [comment]
Awesome, that's very helpful - thanks!
