### ISSUE TITLE
[BUG] Chaining query string options doesn't seem to be working anymore

### ISSUE THREAD

**Issue by lkucytowski** [NemesisRE/kiosk-mode#145]
**Describe the bug**
Chaining query string options in the URL seems to be broken now, was working fine till 4.6.0.

http://10.0.0.11:8123/lovelace/tablet-main?hide_header - this hides a header as expected
http://10.0.0.11:8123/lovelace/tablet-main?hide_sidebar - this hides a sidebar as expected
http://10.0.0.11:8123/lovelace/tablet-main?hide_header?hide_sidebar - this doesn't hide anything

**To Reproduce**
Use two or more options in the URL

**Expected behavior**
Both sidebar and header should be hidden when options **?hide_header?hide_sidebar** are being passed

**Versions:**
 - Home Assistant: 2023.11.3
 - Kiosk-Mode 4.6.0

**Comment by NemesisRE** [comment]
Hi, this should have never been working, if it did it was a bug before. The usual way to chain them is with '&' like that 
http://10.0.0.11:8123/lovelace/tablet-main?hide_header&hide_sidebar

**Comment by lkucytowski** [comment]
Nice one 😅 Closing the ticket then, thanks for doing this!

**Comment by elchininet** [comment]
Indeed, the previous implementation was buggy not only with clear cache parameters.

Previously, parameters in the URL were checked with:

```typescript
window.location.search.includes(param)
```

Which returns `true` for that malformed URL, but also returns `true` with wrong parameters as:

`?xxxxhide_headeryyyyy`

Currently we check the URL parameters using [URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams):

```typescript
new URLSearchParams(window.location.search).has(param)
```

Which returns `false` with that malformed URL just because:

```typescript
Array.from(
    new URLSearchParams('?hide_header?hide_sidebar').keys()
)
```

Returns `['hide_header?hide_sidebar']`

Which means that you have only one parameter in the URL in that case and it is `hide_header?hide_sidebar`.

As @NemesisRE mentioned, parameters in the URL are separated by `&`.
