### ISSUE TITLE
[FR] Hide inside panel

### ISSUE THREAD

**Issue by DanyCDev** [NemesisRE/kiosk-mode#168]
**Is your feature request related to a problem? Please describe.**
Hey, I love the project, but I think it would be good if there was a option to disable only the tabs (dashboards, logbook, media etc.) Currently you can only disable the main sidebar. 
**Describe the solution you'd like**
I Would be really happy if you would manage to implement a feature, where the tabs are hidden from the user, but notifications and account is still shown!

**Comment by DanyCDev** [comment]
And if possible, it would be amazing for it on mobile to not display the tabs, but still display the "App Configuration" menu. thanks!

**Comment by elchininet** [comment]
Hi @DanyCDev,

Are you referring to the sidebar items?

![image](https://github.com/NemesisRE/kiosk-mode/assets/3728220/9ec8acd2-14d8-402f-a95c-d33d814bb5c9)

**Comment by DanyCDev** [comment]
Yes this one

**Comment by elchininet** [comment]
Hi @DanyCDev,
Click on your user account, search for `Change the order and hide items from the sidebar`, and click on `edit`. Then you can remove or reorder the sidebar items.

**Comment by DanyCDev** [comment]
Yes, thank you, but that is only for 1 session, so if i log out and log in, it will show them again. Would it be possible to just not show the stuff in the sidebar, but show notif, and acc? Thanks.

**Comment by elchininet** [comment]
Hi @DanyCDev,

Unfortunatelly, that falls out of the scope of `kiosk-mode` which is intended to hide critical elements that are fixed (they are present on every Home Assistant installation) with the intention of show it in a kiosk device.

If you want a more permanent solution, [there are plugins that are built to perform that task](https://github.com/xZetsubou/ha-custom-sidebar) or you can use [card-mod](https://github.com/thomasloven/lovelace-card-mod) if you want to achieve a more personalised result.

I am planning from some time to build a plugin to manage the sidebar because the ones that are there are not hevaily maintained. I‘ll let you know if I create one that satisfies your needs.

Regards
