### ISSUE TITLE
Scroll/swiping goes beyond top of view

### ISSUE THREAD

**Issue by lenwar** [NemesisRE/kiosk-mode#20]
On iOS 16.3 (current stable) and iOS 16.4 (public beta 4) I have the following strange behaviour.

When the header bar is hidden, I can swipe/scroll higher than the top of the view (as if the view is longer than my screen). I tested this on iPhone 11s in case that is relevant.

On iOS 15.x and iOS 12.x the behaviour is fine. (( on older devices I tested with ))

With header hidden:
https://user-images.githubusercontent.com/3773186/226207332-0c05b2ac-09d1-4b94-a8b7-cbee559920b8.MOV

With header shown:
https://user-images.githubusercontent.com/3773186/226207370-5bb63c29-cd54-4b9f-b805-fe497906dceb.MOV

Edit for completeness: The behaviour is equal in the app and the mobile site on the tested devices.
Everything is normal on a Windows 11 desktop with Firefox.

I am currently using HA 2023.3.5 ((current stable)) and using Kiosk Mode 1.7.8 (( current stable ))

I'm not sure when I first noticed it. It has been going on for a while.

**Comment by elchininet** [comment]
Hi @lenwar,

I really don‘t have an explanation about why on your side, this only happens when you have the `hide_header` of `kiosk-mode` enabled.

I have tested on my girlfriend‘s device (same as yours, iPhone 11 / iOS 16) and indeed, I was able to reproduce it. I was able to scroll and hide the top content on the viewport, but in my case it doesn‘t matter if I have `hide_header` or not, it is the default behaviour.

To try this out as cleaner as possible, I have set up a fresh IOS device in Xcode simulator, I set up a fresh Home Assistant instance with Docker, did the onboarding and this is the result on the home screen:

![ios screencast](https://user-images.githubusercontent.com/3728220/226476159-42b419eb-3d91-4f16-9b5f-a53217669194.gif)

It makes sense that this happens, I was debugging the styles and Home Assistant relies a lot on `100vh` for the height of the elements (`kiosk-mode` also uses it for the height of the viewport when the `header` is hidden), [and this is widely known to be problematic on iOS](https://medium.com/quick-code/100vh-problem-with-ios-safari-92ab23c852a8).

![image](https://user-images.githubusercontent.com/3728220/226477520-02b9bd0c-602b-4446-ad60-1b88c342d990.png)

![image](https://user-images.githubusercontent.com/3728220/226477924-5a7d9fda-5150-4f08-b7cf-f73f3157b12c.png)

As I mentioned, I really don‘t know why on your side you are not getting this behaviour by default, but in this case, I think that there is no much that could be done to mitigate the issue that you are having.

**Comment by lenwar** [comment]
Good news :)
I'm currently using the statically compiled version to resolve the issue using HA 2023.4 which is referred to in: https://github.com/NemesisRE/kiosk-mode/issues/27
That version also resolves this scrolling issue for me.

The link to the compiled version is here: https://github.com/NemesisRE/kiosk-mode/issues/27#issuecomment-1492972660
So, once that fix is implemented, this one can be closed too! :)

**Comment by elchininet** [comment]
HI @lenwar,
It seems that it is not the new version the one that solves the issue, it is Home Assistant 2023.4 which has changed the element that scrolls (now it is the `#view` element instead of the `body` of the page). The only change in #27 is making the library select the proper elements that were renamed or removed, nothing more.
Good to know that it is working for you again.

**Comment by elchininet** [comment]
Hi @lenwar,
The new version has been released, closing this issue.
Regards.
