### ISSUE TITLE
Admin account with limited access to Settings page and sections and prevent entity_id change

### ISSUE THREAD

**Issue by samuele2723** [NemesisRE/kiosk-mode#231]
Hello everyone, i would need to keep admin account for some people of my family to make them able to:

- create automations
- rename voice assistant entities
- activate or deactivate exposure to voice assistant of entities

at the same time, i dont want that:

- make updates
- access addons
- access home assistant cloud
- access dashboard page
- access system page

is there any chance to limit access to this page sections?

![image](https://github.com/NemesisRE/kiosk-mode/assets/66970905/7b554de1-9c49-4011-ad0c-5c04c525ed8f)

moreover, i would like to prevent edit entity_id in this panel

![image](https://github.com/NemesisRE/kiosk-mode/assets/66970905/edb777c1-68b9-4e1d-ab65-01943c51937b)

Thanks Nemesis for your awesome work!

**Comment by elchininet** [comment]
Hi @samuele2723,

`kiosk-mode` is a lovelace plugin, and it is intended, as its description states, to work only on lovelace dashboards.

What you are searching is out of the scope of this plugin because it will not work outside a lovelace dashboard.

On top of the previous, `kiosk-mode` is not an RBAC solution, and due to your specific use case of limiting certain admin users to do certain actions, you are searching for some kind of Role Based Access Control and that is something that should be provid by Home Assistant itself and not by a simply JavaScript plugin.

Regards
