### ISSUE TITLE
[FR] Allow hiding sidebar items (map, logbook, etc)

### ISSUE THREAD

**Issue by clau-bucur** [NemesisRE/kiosk-mode#248]
**Is your feature request related to a problem? Please describe.**
It would be great to allow hiding certain sidebar buttons from non-admin users, or even altogether.

**Describe the solution you'd like**
Ability to hide the following buttons: Map, Logbook, History, Media, Calendar.

**Describe alternatives you've considered**
Using `custom-sidebar` lovelace plugin but it misses a general "non-admin" approach, which `kiosk-mode` does.

Thank you.

**Comment by elchininet** [comment]
Hi @clau-bucur,

`Kiosk-mode` is intended to hide elements only in Lovelace dashboards, and the sidebar is present in every dashboard even if it is not a Lovelace one. On top of that elements in the sidebar are not fixed, every user has their own, and `kiosk-mode` only works with fixed elements.

As you mentioned, there is a specific custom plugin to do that, if that plugin doesn't have a certain feature, it makes more sense to request that feature there instead of requesting it in a plugin that is not intended to perform those tasks.

Regards
