### ISSUE TITLE
[BUG]  header not hide

### ISSUE THREAD

**Issue by nelsonamen** [NemesisRE/kiosk-mode#304]
No theme select

**Screenshots**
![Screenshot_2024-11-12-13-56-50-316_io homeassistant companion android](https://github.com/user-attachments/assets/8c1eca08-da55-4402-a480-ff3909f6c05e)

![Screenshot_2024-11-12-13-55-31-880_io homeassistant companion android](https://github.com/user-attachments/assets/084938b1-b496-425c-8f03-d967c9aab485)
![Screenshot_2024-11-12-13-55-19-339_io homeassistant companion android](https://github.com/user-attachments/assets/740fd43a-d7e8-4c70-97e8-ed4ec6726c33)

**Versions:**
 - Home Assistant: [e.g. 2024.11.2]
 - Kiosk-Mode [e.g. v6.4.0]

**Additional context**

**Comment by elchininet** [comment]
Hi @nelsonamen,

Consult the [user_settings section](https://github.com/NemesisRE/kiosk-mode?tab=readme-ov-file#user_settings). `users` should be an array, not a string. Before we had a code that transformed everything to an array so it is possible that if you wrongly were using a string it worked because it was converted to an array, this is not happening anymore:

```yaml
kiosk_mode:
  user_settings:
    - users:
        - "casa"
      hide_header: true
```

**Comment by nelsonamen** [comment]
👍 works!
Thanks.
