### ISSUE TITLE
Top bar feature request

### ISSUE THREAD

**Issue by pepe59** [NemesisRE/kiosk-mode#48]
Would it be possible to add a function: move the top bar to the bottom edge?
I was using this option with code, but after the HA 2023.4 update it went back up and I couldn't find an option to bring it back down.
I find the upper bar located at the bottom more effective for controlling pages. Thank you.

**Comment by elchininet** [comment]
Hi @pepe59,
That falls out of the scope of this plugin that its main purpose is to hide elements for kiosk devices, you would need to check if someone forked the [custom-header plugin](https://github.com/maykar/custom-header) and it is maintaining it because that complement was written exactly to achieve things like that.
Regards

**Comment by elchininet** [comment]
Hi @pepe59,
There is a new documentation for [kiosk-mode complements](https://github.com/NemesisRE/kiosk-mode/blob/master/KIOSK-MODE-COMPLEMENTS.md#move-the-header-to-the-bottom) that contains the necessary steps to achieve what you were searching.
Regards
