### ISSUE TITLE
Buttons

### ISSUE THREAD

**Issue by adamj3000** [NemesisRE/kiosk-mode#57]
Hi,

After today's update buttons are not displaying

![image](https://user-images.githubusercontent.com/65854745/231672242-38bf1e44-f2ad-4b6c-aeb4-1c1a2d6331e2.png)

![image](https://user-images.githubusercontent.com/65854745/231672342-1d409d8a-2f98-42b7-93d6-df9cedcc83af.png)

Any advise?

**Comment by elchininet** [comment]
Hi @adamj3000,
Please, describe better your issue.
* What update are you referring to?
* What buttons are you referring to?
* What do you expect and what you are getting?
* How is your issue releted to `kiosk-mode`?
* Regards

**Comment by adamj3000** [comment]
Thank you for your quick reply. I got a notification to update Kiosk after that buttons not showing in the grid card configuration

![image](https://user-images.githubusercontent.com/65854745/231675034-bff4da3a-10ac-4c80-a74a-c37d57928313.png)

before update all was good.

**Comment by adamj3000** [comment]
Thank you for your advice. I uninstalled and it's still the same.

**Comment by elchininet** [comment]
Perfect @adamj3000,
You need to figure it out what could be causeing the issue. I recommend you to first check those entities and check if the same happens if you create a new button, if you don‘t find it, then follow the same as you did, disabling or uninstalling one by one your themes / custom cards and check if the issue is solved to find what is causing it.
Regards
