### ISSUE TITLE
Add fullscreen mode?

### ISSUE THREAD

**Issue by Littleislandbrewing** [NemesisRE/kiosk-mode#70]
Any chance of adding fullscreen mode to when the dashboard loads without having to click a button?

[KTibow/fullscreen-card](https://github.com/KTibow/fullscreen-card)

**Comment by elchininet** [comment]
Hi @Littleislandbrewing,
That falls more on the scope of `fullscreen-card` instead of `kiosk-mode`, but anyway it is good that you know that it is not possible, [for security reasons](https://stackoverflow.com/a/7934009/2035354), fullscreen mode [should be initiated by a user interaction](https://developer.mozilla.org/en-US/docs/Web/API/Element/requestFullscreen#security).
Regards

**Comment by elchininet** [comment]
@Littleislandbrewing,
By the way, if you are going to use this in an Android wall tablet or any other device to be used as a kiosk device, I recommend you [Fully Kiosk](https://www.fully-kiosk.com/).
Regards

**Comment by Littleislandbrewing** [comment]
Its to be used on a x86 tablet using chrome and the idea was to stop (morons) from navigating using the browser. 

I know you can set a x86 up in kiosk mode, however should the user navigate to the HA URL using say a dsesktop or from home i cant force "windows kiosk mode" without them "accepting" fullscreen mode

This was just a way of making sure HA always went into fullscreen mode without any user interaction

**Comment by elchininet** [comment]
Hi @Littleislandbrewing,

As I mentioned, all your needs could be solved at the moment with [fully-kiosk](https://www.fully-kiosk.com/) using an Android device. Users cannot go to home, they don't have access to the address bar and no other application can be opened if you set it up in that way.

Unfortunately, using a regular browser, there are certain things that you cannot bypass because of security concerns.

Regards
