### ISSUE TITLE
[FR] add functionality to keep menu itself, after disabling all items 

### ISSUE THREAD

**Issue by Mariusthvdb** [NemesisRE/kiosk-mode#79]
only thing I feel that should still be addressed is that when all items are disable, the whole spot in the menubar is deleted. I still need/would love my template there to be functional in that case.

as [per request](https://github.com/NemesisRE/kiosk-mode/issues/78#issuecomment-1571516089

hope you will consider.

with either of the menu items still enabled:

<img width="415" alt="Scherm­afbeelding 2023-06-01 om 09 50 57" src="https://github.com/NemesisRE/kiosk-mode/assets/33354141/0fd37339-47a5-4444-87a7-c0a14547e1f3">

after disabling all menu items via:

<img width="501" alt="Scherm­afbeelding 2023-06-01 om 09 51 37" src="https://github.com/NemesisRE/kiosk-mode/assets/33354141/a4ee2e8c-d630-44bd-b54d-a0f73bde9751">

we are deprived of our menu in the header:

<img width="499" alt="Scherm­afbeelding 2023-06-01 om 09 51 42" src="https://github.com/NemesisRE/kiosk-mode/assets/33354141/7a47ae12-dedc-4648-bda2-504bcfc62f37">

**Comment by Mariusthvdb** [comment]
cool! lets have it, Im ready ;-)

<img width="476" alt="Scherm­afbeelding 2023-06-01 om 22 21 47" src="https://github.com/NemesisRE/kiosk-mode/assets/33354141/22df4845-071e-4ffb-9e8b-481ee9301eb1">

**Comment by elchininet** [comment]
@Mariusthvdb,
A new version has been released, test it and let me know.
Regards

**Comment by Mariusthvdb** [comment]
nice, seems to be working very well.

added the boolean in the helpers, and the config in kiosk-mode settings:

```
# Hide overflow on empty menu-items
  - entity:
      input_boolean.auto_hide_overflow: 'on'
    auto_hide_overflow: true
```

makes the overflow hide nicely. (I do find the name confusing, as I also have an overflow selector that actually looks at overflowing menubars... but, thats a naming convention we could have a look at)

when Not hidden, but with all menu items hidden individually there's some recollection of a menu left:

<img width="246" alt="Scherm­afbeelding 2023-06-02 om 07 18 16" src="https://github.com/NemesisRE/kiosk-mode/assets/33354141/3460fcae-9f4f-4286-a0cd-9faf912f5d90">

and even the popup linking to the dashboard options:

<img width="255" alt="Scherm­afbeelding 2023-06-02 om 07 23 07" src="https://github.com/NemesisRE/kiosk-mode/assets/33354141/c1562454-9113-4c67-b9c7-9d8fb9be55d7">

There would be no options to prevent that I guess?

also, this is nice:

<img width="294" alt="Scherm­afbeelding 2023-06-02 om 07 28 11" src="https://github.com/NemesisRE/kiosk-mode/assets/33354141/6332e627-acdd-40ad-9abb-f5ca71d25291">

**Comment by elchininet** [comment]
Hi @Mariusthvdb,

Good to know that it is working. The "recollection of a menu left" is the reason why it was previously hidden by default. I wanted to make it hidden by default and implement an option to show it, but everything in `kiosk-mode` (including the query parameters) tries to hide things, not to show them, so I decided to do it in the other way around and if someone wants to put something inside the menu using CSS (as you are doing with the three-dots), it is also possible.

About hiding it completely, you can do it using some custom CSS rules, let me know if you need help with them.

Good to know that the `console.info` is also working for you.

Regards

**Comment by Mariusthvdb** [comment]
> About hiding it completely, you can do it using some custom CSS rules, let me know if you need help with them.

well, tbh, yes that would be appreciated.

I guess we would need to only use that if
- all times are hidden
- the auto-hide-overflow is off

in all other cases the menu should respond as per HA core design ;-)

would you suggest doing that in card_mod? or what did you have in mind?

**Comment by elchininet** [comment]
Hi @Mariusthvdb,

I'll take a look on Monday. Yes, basically it is doing something similar to what you did to display your weather card. 

Thinking out loud, maybe that could be the solution since the beginning because I think that not many users will want the menu visible if everything is hidden, but I'll help you with that next week.

Regards

**Comment by elchininet** [comment]
Hi @Mariusthvdb,

I was thinking about the next points:

1. The majority of users will prefer to auto-hide the overflow menu if everything is hidden
2. Indeed, the name of the new option is confusing
3. To reach the level of personalisation that you are searching, there are needed custom styles anyway

Taking into account the previous points, I think that it would be better to revert the `auto_hide_overflow` option. What you want to do, could be achieved through custom styles using a card mod theme. But I need that you test this first before doing any change:

1. Go to [the latest gist](https://gist.github.com/elchininet/9a2648ea0016d3194072712c745c5ad2) and install it manually (it is a revert of the `auto_hide_overflow` option)
2. In your card mod theme try to do something like this (this is basically an override of the styles that `kiosk-mode` applies). You will need to name the variables properly depending on the names of your `input_booleans`.

```yaml
your-theme:
    card-mod-theme: your-theme
    card-mod-root: |
    {% set kiosk_hide_overflow = states('input_boolean.kiosk_hide_overflow') %}
    {% set kiosk_hide_search = states('input_boolean.kiosk_hide_search') %}
    {% set kiosk_hide_assistant = states('input_boolean.kiosk_hide_assistant') %}
    {% set kiosk_hide_refresh = states('input_boolean.kiosk_hide_refresh') %}
    {% set kiosk_hide_unused_entities = states('input_boolean.kiosk_hide_unused_entities') %}
    {% set kiosk_hide_reload_resources = states('input_boolean.kiosk_hide_reload_resources') %}
    {% set kiosk_hide_edit_dashboard = states('input_boolean.kiosk_hide_edit_dashboard') %}

    {% set all_hidden_storage_desktop = kiosk_hide_edit_dashboard == 'on' and kiosk_hide_overflow == 'off' %}
    {% set all_hidden_storage_mobile = all_hidden_storage_desktop and kiosk_hide_search == 'on' and kiosk_hide_assistant == 'on' %}

    {% set all_hidden_yaml_desktop = kiosk_hide_edit_dashboard == 'on' and kiosk_hide_refresh == 'on' and kiosk_hide_unused_entities == 'on' and kiosk_hide_reload_resources == 'on' and kiosk_hide_overflow == 'off' %}
    {% set all_hidden_yaml_mobile = all_hidden_yaml_desktop and kiosk_hide_search == 'on' and kiosk_hide_assistant == 'on' %}

    /* Do not hide the overflow menu in desktop in storage mode */
    {% if all_hidden_storage_desktop %}
      .header .toolbar > .action-items > ha-button-menu[data-lovelace-mode="storage"][data-children="1"] {
        display: block !important;
        pointer-events: none !important;
      }
    {% endif %}

    /* Do not hide the overflow menu in mobile in storage mode */
    {% if all_hidden_storage_mobile %}
      .header .toolbar > .action-items > ha-button-menu[data-lovelace-mode="storage"][data-children="3"] {
        display: block !important;
        pointer-events: none !important;
      }
    {% endif %}

    /* Do not hide the overflow menu in desktop in yaml mode */
    {% if all_hidden_yaml_desktop %}
      .header .toolbar > .action-items > ha-button-menu[data-lovelace-mode="yaml"][data-children="4"] {
        display: block !important;
        pointer-events: none !important;
      }
    {% endif %}

    /* Do not hide the overflow menu in mobile in yaml mode */
    {% if all_hidden_yaml_mobile %}
      .header .toolbar > .action-items > ha-button-menu[data-lovelace-mode="yaml"][data-children="6"] {
        display: block !important;
        pointer-events: none !important;
      }
    {% endif %}
```

Let‘s try to make it work for you and when you test it then I‘ll revert the `auto_hide_overflow` option.

Regards

**Comment by Mariusthvdb** [comment]
hi, and thanks for taking all of this time and effort. wow, appreciated!!

please let me respond:

> Taking into account the previous points, I think that it would be better to revert the auto_hide_overflow option.

not really sure about that tbh. yes default should be as you say, auto-hide. However, custom styling is very very fragile using card_mod, so even though an option, imho it would be best to take care of in the Kiosk mode integration. especially since using children in these mods is terribly 'hard-coded' and deepening 

if that would mean we have the 'remnant' upon disabling auto-hide, I would even prefer that above having all of those stylings that break upon each and every frontend/card_mod change...especially since using 'children' in these mods. if anything we should try and mod labels or id's.

My take would be: if people don't need it, they won't use it, and wouldn't be bothered by it, if they are not confronted with it. And they aren't, because of the default auto-hide.

let me try and test your mods though.
I believe it would be a bit easier to have a binary based on all of the above, and use that binary inside the card_mod:

```
template:

  - binary_sensor:

      - unique_id: kiosk_mode_all_menu_items_hidden
        state: >
          {{is_state('input_boolean.hide_refresh','on') and
            is_state('input_boolean.hide_unused_entities','on') and
            is_state('input_boolean.hide_reload_resources','on') and
            is_state('input_boolean.hide_edit_dashboard','on')}}

      - unique_id: kiosk_mode_show_overflow_with_all_menu_items_hidden
        state: >
          {{is_state('binary_sensor.kiosk_mode_all_menu_items_hidden','on') and
            is_state('input_boolean.auto_hide_overflow','off')}}
```

meaning:

if all menu items are hidden And auto-hide = 'off', show overflow.
In all other cases, dont show overflow.

that way we would only need to hide the 'remnant' when kiosk_mode_show_overflow_with_all_menu_items_hidden = 'on'

and that would  be an explicit user setting, overriding the default, I believe that is what we all agree on?

ill test the card mod next, first by trying to mod the remnant as is, to see if that actually does anything

**Comment by Mariusthvdb** [comment]
summarize in consolidated post:

all it takes it this simple card-mod-theme mod:
```
      ha-button-menu {
        pointer-events: {{'none !important' if is_state('binary_sensor.kiosk_mode_show_overflow_with_all_menu_items_hidden','on')}};
      }
```

and the extra binary sensors:

```
template:

  - binary_sensor:

      - unique_id: kiosk_mode_all_menu_items_hidden
        state: >
          {{is_state('input_boolean.hide_refresh','on') and
            is_state('input_boolean.hide_unused_entities','on') and
            is_state('input_boolean.hide_reload_resources','on') and
            is_state('input_boolean.hide_edit_dashboard','on')}}

      - unique_id: kiosk_mode_show_overflow_with_all_menu_items_hidden
        state: >
          {{is_state('binary_sensor.kiosk_mode_all_menu_items_hidden','on') and
            is_state('input_boolean.auto_hide_overflow','off')}}
```

to have all you want (on the current release version of Kiosk mode:
- auto-hide-overflow on hide of all menu items by default, no user interaction required

allow individuals users to explicitly keep the overflow menu (eg incase of template text shown) and not show the popup on the menu or the remnant empty box

100% score!

**Comment by elchininet** [comment]
Hi @Mariusthvdb,

About this:

>not really sure about that tbh. yes default should be as you say, auto-hide. However, custom styling is very very fragile using card_mod, so even though an option, imho it would be best to take care of in the Kiosk mode integration. especially since using children in these mods is terribly 'hard-coded' and deepening

That‘s right, custom styles are very fragile, also if they are provided by `kiosk-mode`, so having them inside `kiosk-mode` just moves the problem to somewhere else and makes `kiosk-mode` more likely to fail in future updates. That‘s why it is necessary to provide just the necessary functionality without too much unnecessary complexities.

Previously, I thought about hidding the overflow menu by default if all its children were hidden and avoid doing this if some option is present, but it has its drawbacks:

* It goes in an opossite direction from the rest of the options. All the options are intended to "hide" things, having one to "show" something that got hidden before by the same library is contraintuitive.
* It would be an option that will only work if other options are used together, the rest of the time it does nothing, this is also contraintuitive and it is not aligned with the rest of the options that they simply hide something if they are used.
* It also adds confussion when it is used as a query parameter. Query parameter are intended to hide something adding them in the URL, this would require adding this option together with other options to make it work, rest of the time it does nothing.

I also thought about adding it as an `ignore_` option like `ignore_entity_settings`, `ignore_mobile_settings` or `ignore_disable_km`, but these ones are intended to ignore an option or a section in the configuration, no to ignore a set of options used together. It is also hard to name the option in such way that it is descriptive enough to communicate what it does.

If you have some ideas about how to make an option that doesn‘t add confussion and it is not contraintuitive and at the same time fits your purpose just let me know your thoughts, but I feel that right now this option is not adding any value, it is just adding complexity and confussion.

About the second topic. The complexity of the styles that I gave you, is just because they are applied dynamically taking into account other options. It is just a replication of what `kiosk-mode` does at the moment but in reverse mode (showing what it has hidden before). If you just decide "I want to show the icon of the overflow menu no matter what because I use it to put something inside it", you just need somehting like this:

```css
.header .toolbar > .action-items > ha-button-menu[data-lovelace-mode][data-children] {
    display: block !important;
    pointer-events: none !important;
}
```

It will show the element no matter what and will override any `kiosk-mode` option (even `hide_overflow`).

#### These are some responses to your questions:

>Aren't you trying to block this remnant (the now empty mwc-list box)?

Yes, adding `pointer-events: none` makes the overflow menu icon ignore mouse clicks, so it will not open anything and it will not show anything on mouse over.

>You are pointing to the individual menu items??

I am pointing to input booleans that make `kiosk-mode` apply the options that hide the menu items. In this way it appllies the custom styles only if these options were used.

>I believe it would be a bit easier to have a binary based on all of the above, and use that binary inside the card_mod:

Yes, you can use whatever tehnique Home Assistant provides to organise the templates, a binary sensor it is a good way to reduce the template complexity.

>if all menu items are hidden And auto-hide = 'off', show overflow. In all other cases, dont show overflow.

In the code that I provided you, there is no `auto_hide` option, it assumes that this option was cleaned (that‘s why I mentioned to try with the gist that have the library with this option removed). It applies the styles if the options to hide the children have been used and the option to hide the overflow menu has not been used (trying to avoid showing the menu if it was explicity hidden)

>that way we would only need to hide the 'remnant' empty box when kiosk_mode_show_overflow_with_all_menu_items_hidden = 'on'

It is an option, yes

>and that would be an explicit user setting, overriding the default, I believe that is what we all agree on?

No, the option that is implemented right now doesn‘t tell you if the items inside the overflow are hidden or not, it is just that it works only if the other options are enabled. This is not the same as having a binary sensor that tells you that all the options are hidden and the overflow has not been hidden on purpose (this is whay is being provided in the code that I gave you)

>shouldnt we be able to set display: none to mwc-list directly?

It is inside the `shadowDOM` and inside a slot, if you are able the reach it with some `$` magic it would be possible, but I find it easier just to block the mouse events of the button, so it will not show that element and also it will not show the title when you rollover it.

**Comment by elchininet** [comment]
About your second post with the summary,

Just replace `is_state('input_boolean.auto_hide_overflow','off')` with `is_state('input_boolean. hide_overflow','off')` and then add `display: block` to the `ha-button-menu` adding the specificity that I gave you before `.header .toolbar > .action-items > ha-button-menu[data-lovelace-mode][data-children]` and the `auto_hide_overflow` could be discarded.

My point about removing it was because it is not adding much for the majority of users, and for users that want something very personalised, as you, it doesn‘t add much because you still need to create a binary sensor and a custom mod style, something that you can also do without this option.

**Comment by elchininet** [comment]
Just let‘s brainstorm a bit to check if this option really brings a value, and if it does, let‘s try to rename it or refactor it in a way that doesn‘t create confusion as it creates right now.

**Comment by Mariusthvdb** [comment]
trying to consume you with post above, I have to admit you are making things more complicated than I intended to ask for.
Imho, a bit too difficult.

My binary works perfectly, but then again, I do have set all available options in Kiosk-mode selectable via booleans . In my case, it does exactly what I say it does.

'Most users' will not have these booleans at all, and for them all of this would not be relevant.
The users I do know that have these set, will appreciate the possibility a lot, especially since those users mostly use card-mod to do something with the header..

(if we can speak about 'most users' in the first place, I have no idea how many those are)

Trying to limit user configurable yaml code, I feel my solution fits the bill, as it minimizes exactly that.
(agree on the `pointer-events: none`, which I also use in my card_mod)

not sure what you want me to do further.

given the fact you will use the auto-hide dashboard menu (thats what it is called in the frontend, so maybe use that terminology)

<img width="220" alt="Scherm­afbeelding 2023-06-06 om 20 45 42" src="https://github.com/NemesisRE/kiosk-mode/assets/33354141/62196b3f-a0ad-4ffd-9358-4ad93d954f90">

as default setting when all menu-items are hidden (and which I fully support), there's only 1 choice I suggest:
add an option to override that using a config option like currently available.

I have to read with more attention, but just figured you deserved a swift response! so forgive me if I didnt touch everything yet.

**Comment by elchininet** [comment]
>Trying to consume you with post above, I have to admit you are making things more complicated than I intended to ask for.

Please, read it entirely, you already have a custom binary sensor with eleven lines and a custom style to do what you are doing. What I am trying to tell you is that you can do the same with the same eleven lines of the binary sensor and a custom style (but without the necessity of having an extra option that it is not giving you to much to you or to any user).

That option would be useful for you if you don‘t need to do the above, but if you need to do it to reach the level of personalisation that you are searching, what is the benefit of the option?

So, instead having this:

* If:

    * is_state('input_boolean.hide_refresh','on')
    * is_state('input_boolean.hide_unused_entities','on')
    * is_state('input_boolean.hide_reload_resources','on') 
    * is_state('input_boolean.hide_edit_dashboard','on')
    * is_state('input_boolean.auto_hide_overflow','off')

* Make the button non-interactive

You could have this:

* If:

    * is_state('input_boolean.hide_refresh','on')
    * is_state('input_boolean.hide_unused_entities','on')
    * is_state('input_boolean.hide_reload_resources','on') 
    * is_state('input_boolean.hide_edit_dashboard','on')
    * is_state('input_boolean.hide_overflow','off')

* Make the button non-interactive **and show it**

The only thing that is making things "more complicated" is the previous bold statement that is not present in your current configuration 🙂

If I find a way of refactoring the option in a way that doesn‘t create confussion (and I didn‘t noticed it when i implemented it) we can maintain it, but at the moment it is not adding too much value, it just complicates the logic of `kiosk-mode` and  creates confussion.

Please, try what I recommended using the guist to see if it works and let me know.

**Comment by elchininet** [comment]
About this:

>change:
>auto_hide_overflow: true
>to
>auto_hide_dashboard_menu: true

That element is named `overflow` in the library, the option to hide it is `hide_overflow`, if there is an option that influences its behaviour, should be named properly, if it is named differently it creates more confusion.

About making it `true` by default, I explained it before, it is not good, all the options are false by default and they are enabled to hide things. All the query parameters are intended to hide things, so it is needed just to add the query parameter without any value. If we want to disable that option as a query parameter, `?auto_hide_dashboard_menu` by itself doesn‘t work, the only way to do it is doing something like ?`auto_hide_dashboard_menu=false` or something similar that goes in the opossite direction of the other query parameters and just creates confusion.

**Comment by elchininet** [comment]
Hi @Mariusthvdb,

I have solved it, I was thinking on this harder and I don‘t know how it didn‘t come to my mind before.
The idea basically is that there are no assumptions, if one wants to hide something, one needs to specifically do it, so no hidden elements by default and no "auto hide" option that was annonying me after implementing it, you need to specifically hide whatever you want to hide. This reduces the complexity of the code a lot and helps users that want to have complete control of the personalisation because it gives you everything by default (no custom binary sensor, no custom card mod styles).

Basically `auto_hide_overflow` is gone and two new options are available: `hide_overflow_list` and `block_overflow`. Instead of explaining to you what are the options and how to use them, it is better if I paste here the new version of the README, so you can have access to the new documentation that I am preparing.

You can have access to the early code in [the guist](https://gist.github.com/elchininet/9a2648ea0016d3194072712c745c5ad2), it would be helpful for me if you test it deeply.

## Config Options

| Config Option            | Type    | Default | Description |
|:-------------------------|:--------|:--------|:------------|
|`kiosk:`                  | Boolean | false   | Hides both the header and sidebar. |
|`hide_header:`\*          | Boolean | false   | Hides only the header. |
|`hide_sidebar:`           | Boolean | false   | Hides only the sidebar. |
|`hide_menubutton:`\*      | Boolean | false   | Hides only the sidebar menu icon. |
|`hide_overflow:`          | Boolean | false   | Hides the top right overflow menu. |
|`hide_overflow_list`      | Boolean | false   | Hides the top right overflow menu list |
|`hide_account:`           | Boolean | false   | Hides the account icon. |
|`hide_search:`            | Boolean | false   | Hides the search icon. |
|`hide_assistant:`         | Boolean | false   | Hides the assistant icon. |
|`hide_edit_dashboard`     | Boolean | false   | Hides the "Edit dashboard" button inside the top right overflow menu |
|`hide_refresh`            | Boolean | false   | Hides the "Refresh" button inside the top right overflow menu in lovelace yaml mode |
|`hide_unused_entities`    | Boolean | false   | Hides the "Unused entities" button inside the top right overflow menu in lovelace yaml mode |
|`hide_reload_resources`   | Boolean | false   | Hides the "Reload resources" button inside the top right overflow menu in lovelace yaml mode |
|`block_overflow`          | Boolean | false   | Blocks the top right overflow menu mouse interactions |
|`block_mouse:`            | Boolean | false   | Blocks completely the mouse. No interaction is allowed and the mouse will not be visible. **Can only be disabled with `?disable_km` query parameter in the URL.** |
|`ignore_entity_settings:`\** | Boolean | false   | Useful for [conditional configs](#conditional-lovelace-config) and will cause `entity_settings` to be ignored. |
|`ignore_mobile_settings:`\*\*\* | Boolean | false   | Useful for [conditional configs](#conditional-lovelace-config) and will cause `mobile_settings` to be ignored. |
|`ignore_disable_km:`\**      | Boolean | false   | Useful for [conditional configs](#conditional-lovelace-config) and will cause `disable_km` URL parameter to be ignored. |

## Query Strings
Add a query string such as `?kiosk` to the end of your URL:

```
https://hass:8123/lovelace/default_view?kiosk
```

The query string options are:

* `?kiosk` to hide both header and sidebar
* `?hide_header` to hide only the header
* `?hide_sidebar` to hide only the sidebar
* `?hide_overflow` to hide the top right menu
* `?hide_overflow_list` to hide the top right overflow menu list
* `?hide_menubutton` to hide sidebar menu button
* `?hide_account` to hide the account icon
* `?hide_search` to hide the search icon
* `?hide_assistant` to hide the assistant icon
* `?hide_edit_dashboard` to hide the "Edit dashboard" button inside the top right menu
* `?hide_refresh` to hide the "Refresh" button inside the top right menu in lovelace yaml mode
* `?hide_unused_entities` to hide the "Unused entities" button inside the top right menu in lovelace yaml mode
* `?hide_reload_resources` to hide the "Reload resources" button inside the top right menu in lovelace yaml mode
* `?block_overflow` to block the top right overflow menu mouse interactions
* `?block_mouse` to block completely the mouse

**Comment by Mariusthvdb** [comment]
Thanks, better indeed!
whole new idea, that mimics what I was experimenting with yesterday myself!

given the power of `pointer-events: none !important;` I had been testing that, and disabling the overflow boolean too...

and yes that would work fine indeed.

**scenario:** _show, but block overflow if 4 menu options are disabled_
it would require an adapted binary for block overflow, and creation of a selector for that `input_boolean.kiosk_mode_block_overflow`

```
template:

  - binary_sensor:
# this remains the same, for ease of usage elsewhere and in the 'block' binary
      - unique_id: kiosk_mode_all_menu_items_hidden
        state: >
          {{is_state('input_boolean.hide_refresh','on') and
            is_state('input_boolean.hide_unused_entities','on') and
            is_state('input_boolean.hide_reload_resources','on') and
            is_state('input_boolean.hide_edit_dashboard','on')}}

      - unique_id: kiosk_mode_block_overflow
        state: >
          {{is_state('binary_sensor.kiosk_mode_all_menu_items_hidden','on') and
            is_state('input_boolean.kiosk_mode_block_overflow','on')}}
```

in kiosk-mode settings

```
  - entity:
      input_boolean.kiosk_mode_block_overflow: 'on'
    block_overflow: true
```

am I correct?

**Comment by elchininet** [comment]
@Mariusthvdb,

Yes, your approach does the trick of hiding the logic of blocking the menu, so  it will work automatically without the necessity of setting it up manually.

Please, try the code and check if everything works as expected.

Another topic, I left the possibility of hiding the overflow list, letting active the overflow-menu. Now, I am thinking if that could be useful, it is impossible to place interactive elements inside the :after/:before pseudo-elements so what is the benefit of being able to click on it if there is no overflow list? Do you think that would be useful for some cases or is it just an option that could be removed?

Regards

**Comment by Mariusthvdb** [comment]
first part:
ive tested the Gist and yes its working as I set it now, with a tiny variation:
```
# Block mouse on empty overflow menu-items
  - entity:
      binary_sensor.kiosk_mode_block_overflow: 'on'
    block_overflow: true
# Block mouse on overflow menu-items
  - entity:
      input_boolean.kiosk_mode_block_mouse: 'on'
    block_mouse: true
```

and the templates:

```
template:

  - binary_sensor:

      - unique_id: kiosk_mode_selected
        state: >
          {{is_state('select.mode','Kiosk') or is_state('input_boolean.kiosk_mode','on')}}

      - unique_id: kiosk_mode_all_menu_items_hidden
        state: >
          {{is_state('input_boolean.hide_refresh','on') and
            is_state('input_boolean.hide_unused_entities','on') and
            is_state('input_boolean.hide_reload_resources','on') and
            is_state('input_boolean.hide_edit_dashboard','on')}}

      - unique_id: kiosk_mode_block_overflow_with_all_menu_items_hidden
        state: >
          {{is_state('binary_sensor.kiosk_mode_all_menu_items_hidden','on') or
            is_state('input_boolean.kiosk_mode_block_overflow','on')}}
```

this way I set the block mouse to kick in on empty menu items, Or when selected from the option directly. 
Working perfectly now.
![Jun-07-2023 10-00-36](https://github.com/NemesisRE/kiosk-mode/assets/33354141/9ebc67fd-df77-4bfb-8599-7926d2010626)

**Comment by Mariusthvdb** [comment]
> Another topic, I left the possibility of hiding the overflow list, letting active the overflow-menu. Now, I am thinking if that could be useful, it is impossible to place interactive elements inside the :after/:before pseudo-elements so what is the benefit of being able to click on it if there is no overflow list? Do you think that would be useful for some cases or is it just an option that could be removed?


from the top of my head: No, in current state of affairs I couldn't think of a scenario where one would show a list that would be empty. For me, blocking the overflow mouse on an empty list is desired behavior. It's what I do with the above.

Unless........ one would be able to set a different service to that menu overflow. I dont think that is possible. If at all, I havent heard of that. It would be a very nice possibility too.

For that reason, I believe it would be safe to take out that option, and make sure that mouse is always blocked on empty menu list.

I could then take pout all that I made above, and, instead of the 'auto-hide overflow menu on empty list' we had before, we would then have 'auto block mouse on empty list'. 

Perfect ;-)

**Comment by elchininet** [comment]
@Mariusthvdb,

Oh, you already tested it, super! Did you test all other options of the library? The code that you tested have more than 250 lines deleted so it would be good to be sure that it is not creating issues. I have tested on my side, but as you have a totally different set up it would be good to test it in a different scenario.

I was also thinking in what could be the scenario of just hiding the list, by CSS is not possible to change the action of that menu, so its only function will be opening a list that is not visible. I‘ll try to check what could be the use case of that, but if I don‘t find a use case, I‘ll remove it.

I would refrain of making "automatic" actions in the future, not only for the complexity and fragility that it brings to the code but also because it is not intuitive and it is not aligned with the rest of the options and what the library does. It is better for the sake of consistency to keep all the options similar and simple (hide this, block that), anything on top of that (and there are infinite possibilities and use cases) could be done with the power of Home Assistant templating, and the current options brings infinite possibilities to do whatever a template advanced user wants to do.

I‘ll work on the pull request and I‘ll test it deeply in the coming days. You can use the code in the guist for now. I‘ll let you know when it is merged and a new version is released. Thanks for the time spent testing this and thinking on the improvements. 👍🏼

Regards

**Comment by Mariusthvdb** [comment]
yes, Ive tested all config options. All work, and none throw errors in inspector as far as I can spot.

I'll put a lock on the block_mouse, because that is very powerful ;-) (had to open another browser to enable it again.....)

<img width="498" alt="Scherm­afbeelding 2023-06-07 om 11 11 30" src="https://github.com/NemesisRE/kiosk-mode/assets/33354141/dcb2cc94-bb2a-48ec-9adc-6864f4cc24f8">

**Comment by elchininet** [comment]
Thanks @Mariusthvdb, good to hear that you have tested it.
You have fallen in the trap of `block_mouse` :)
It is stated in the README:

>**Can only be disabled with ?disable_km query parameter in the URL.**

It is not so useful in computer devices.
